# docker compose -p monolithic-2-services up -d
services:
  monolithic-database-service:
    container_name: monolithic-mysql-container
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret-root
      MYSQL_DATABASE: monolithic-db
      MYSQL_USER: user-app
      MYSQL_PASSWORD: secret-app
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      retries: 10