# docker compose -p msa-tcc-1-services up -d
services:
  order-database-service:
    container_name: order-mysql-container
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret-root
      MYSQL_DATABASE: order-db
      MYSQL_USER: user-app
      MYSQL_PASSWORD: secret-app
    volumes:
      - ./order_mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      retries: 10
  product-database-service:
    container_name: product-mysql-container
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret-root
      MYSQL_DATABASE: product-db
      MYSQL_USER: user-app
      MYSQL_PASSWORD: secret-app
    volumes:
      - ./product_mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 10s
      retries: 10
  point-database-service:
    container_name: point-mysql-container
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret-root
      MYSQL_DATABASE: point-db
      MYSQL_USER: user-app
      MYSQL_PASSWORD: secret-app
    volumes:
      - ./point_mysql_data:/var/lib/mysql
    ports:
      - 3308:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 10s
      retries: 10
